# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850ed5ad85d402ac8d369b239a0810a951521c35
  rakuten_application_id: 1048039841145576300
  rakuten_affiliate_id: 151639b6.65827bc0.151639b7.962ba16c
  #rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  #rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

test:
  secret_key_base: 850ed5ad85d402ac8d369b239a0810a951521c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  rakuten_application_id: 1048039841145576300
  rakuten_affiliate_id: 151639b6.65827bc0.151639b7.962ba16c
  
  #rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  #rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

